#!/bin/bash

echo "Setting up Vercel environment variables..."
echo ""
echo "You'll need to run these commands manually:"
echo ""
echo "1. Set Solana RPC URL (use a reliable RPC provider):"
echo "   vercel env add VITE_SOLANA_RPC_URL production"
echo "   Recommended options:"
echo "   - Helius: https://devnet.helius.xyz/?api-key=YOUR_API_KEY"
echo "   - QuickNode: https://YOUR-ENDPOINT.devnet.quiknode.pro/YOUR-KEY/"
echo "   - Alchemy: https://solana-devnet.g.alchemy.com/v2/YOUR-API-KEY"
echo "   - Default (less reliable): https://api.devnet.solana.com"
echo ""
echo "2. Set Backend URL (after deploying backend):"
echo "   vercel env add VITE_BACKEND_URL production"
echo "   Value: https://your-backend.railway.app"
echo ""
echo "3. Set Convex URL:"
echo "   vercel env add VITE_CONVEX_URL production"
echo "   Value: https://your-convex-deployment.convex.cloud"
echo ""
echo "Or use the Vercel Dashboard:"
echo "1. Go to https://vercel.com/vistara/flipnsol/settings/environment-variables"
echo "2. Add these environment variables:"
echo "   - VITE_SOLANA_RPC_URL = https://api.devnet.solana.com"
echo "   - VITE_BACKEND_URL = (your Railway backend URL)"
echo "   - VITE_CONVEX_URL = (your Convex URL)"
echo ""
echo "After setting all variables, redeploy with: vercel --prod"